#!/usr/bin/env python3
"""Registry of all SCITEX_AUDIO environment variables.

Provides documentation and template generation for environment configuration.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional


@dataclass
class EnvVar:
    """Environment variable definition."""

    name: str
    description: str
    module: str
    default: Optional[str] = None
    required: bool = False
    sensitive: bool = False


ENV_REGISTRY: List[EnvVar] = [
    # Core
    EnvVar(
        "SCITEX_AUDIO_ENV_SRC",
        "Path to env source file/directory",
        "core",
    ),
    # Relay
    EnvVar(
        "SCITEX_AUDIO_MODE",
        "Audio mode: local, remote, or auto",
        "relay",
        "auto",
    ),
    EnvVar(
        "SCITEX_AUDIO_RELAY_URL",
        "Full relay URL (e.g., http://localhost:31293)",
        "relay",
    ),
    EnvVar(
        "SCITEX_AUDIO_RELAY_HOST",
        "Relay host (combined with port to build URL)",
        "relay",
    ),
    EnvVar(
        "SCITEX_AUDIO_RELAY_PORT",
        "Relay server port",
        "relay",
        "31293",
    ),
    EnvVar(
        "SCITEX_AUDIO_HOST",
        "Relay server bind host",
        "relay",
        "0.0.0.0",
    ),
    EnvVar(
        "SCITEX_AUDIO_PORT",
        "Server/relay port",
        "relay",
        "31293",
    ),
    # Backends
    EnvVar(
        "SCITEX_AUDIO_ELEVENLABS_API_KEY",
        "ElevenLabs API key",
        "backend",
        sensitive=True,
    ),
    # Storage
    EnvVar(
        "SCITEX_DIR",
        "Base directory for audio cache files",
        "storage",
        "~/.scitex",
    ),
    EnvVar(
        "SCITEX_CLOUD",
        "Set to 'true' for browser relay mode (OSC escape)",
        "storage",
    ),
]


def get_env_by_module(module: str) -> List[EnvVar]:
    """Get all environment variables for a module."""
    return [e for e in ENV_REGISTRY if e.module == module]


def get_all_modules() -> List[str]:
    """Get list of all modules with env vars."""
    return sorted(set(e.module for e in ENV_REGISTRY))


def generate_template(
    include_sensitive: bool = True, include_defaults: bool = True
) -> str:
    """Generate a template .src file with all environment variables.

    Parameters
    ----------
    include_sensitive : bool
        Include sensitive variables (API keys) as commented placeholders.
    include_defaults : bool
        Include default values for variables that have them.

    Returns
    -------
    str
        Bash-compatible .src file content.
    """
    lines = [
        "#!/bin/bash",
        "# SciTeX Audio Environment Variables",
        "# Generated by scitex_audio.generate_env_template()",
        "#",
        "# Usage: source this file or set SCITEX_AUDIO_ENV_SRC to this path",
        "#   export SCITEX_AUDIO_ENV_SRC=/path/to/this/file.src",
        "",
    ]

    for module in get_all_modules():
        lines.append(f"# === {module.upper()} ===")
        for env in get_env_by_module(module):
            if env.sensitive and not include_sensitive:
                continue

            if env.description:
                lines.append(f"# {env.description}")

            if env.default and include_defaults:
                lines.append(f'export {env.name}="{env.default}"')
            elif env.sensitive:
                lines.append(f'# export {env.name}="YOUR_{env.name}_HERE"')
            else:
                lines.append(f"# export {env.name}=")
        lines.append("")

    return "\n".join(lines)


def get_env_docs() -> Dict[str, Dict]:
    """Get documentation for all environment variables."""
    return {
        e.name: {
            "description": e.description,
            "module": e.module,
            "default": e.default,
            "required": e.required,
            "sensitive": e.sensitive,
        }
        for e in ENV_REGISTRY
    }


# EOF
